### PR TITLE
Replaced each tab with 4 spaces (s/\t/    /g)

### PR DESCRIPTION
**Pull request by jcguu95**
Feel free to decline this change, as the choice of tabs and choices are a bit controversial and even religious. I hope the changes go through because:

1. This reduces the length of each line of code.
2. I plan to make changes in it. Having the space-style makes future code change review easier to read.

If you like this idea, please let me know but **don't merge it** before considering my other PRs (e.g. https://github.com/digikar99/py4cl2/pull/23). I can always run `s/\t/    /g` on the file.

### CODE REVIEW

**Comment by jcguu95** [comment]
@digikar99 this passes as many tests as your last [commit](https://github.com/digikar99/py4cl2/actions/runs/3425571702/jobs/5706496292) in master.

**Comment by digikar99** [comment]
I'd prefer to keep the tabs, since the length of each line/indentation-per-level can be adjusted according to user preferences using the editor.

**Comment by jcguu95** [comment]
I understand your choice. 

Since I'm going to make more changes to the python file, could we replace tabs to spaces *temporarily*, and switch it back to tabs after I'm done changing? This will make the code change easier to read.

**Comment by digikar99** [comment]
> This will make the code change easier to read.

Are you referring to the tab sizes being 8 on github? Turns out that appending `?ts=4` to the github URL gets you tab sizes of size 4! Eg: https://github.com/digikar99/py4cl2/blob/master/py4cl.py?ts=4

**Pull request closed without merging**
