### PR TITLE
avoid side-effects during macroexpansion

### PR DESCRIPTION
**Pull request by death**
I only tested this on SBCL; interested parties can leave a comment sharing their results.

### CODE REVIEW

**Comment by digikar99** [comment]
Does this allow `py4cl2-tests`? 

Locally, it fails to load, and therefore, seems to require a relook into this.

**Comment by digikar99** [comment]
Also, if I get the intention behind this, the goal is to do minimal work at macroexpansion time. 

OTOH, my intention has been to do minimal work at load time, since one loads libraries again-and-again; what this does help with is to (often, significantly) decrease the load-time of a python module compiled into lisp code. 

I'm not terribly sure if this dichotomy can be avoided; but can also say that my experience with lisp isn't too great.

**Comment by death** [comment]
When compiling a file, macros get expanded.  Then if you load the produced fasl file, macroexpansion no longer happens. If you load the file just after you compiled it, the side effects occurred and all seems well, but if you load the file in a clean environment, you'll get errors because the side effects you relied upon during macroexpansion never happen in that session.

With this code, side effects occur both during compile-time and during load-time. So if you compile a file and load it, they occur twice (also, in general, CL allows repeated macroexpansion for forms that are not compiled). If you load a compiled file into a clean environment, the side effects will occur once.

Macro functions should in general not have side effects.

I did not know about py4cl2-tests. I may look at it soon. Is it possible that it assumes too much?

**Comment by digikar99** [comment]
Okay, I can get py4cl2-tests to load with a small update.

Also, re: measuring things, compiling a file with a `(defpymodule "numpy" nil :lisp-package "NP")` form takes about 1.5 seconds. Then, with the side-effects during macroexpansion time, loading the compiled fasl is superquick at <0.05 seconds at the cost of a large fasl. And the time adds with multiple modules. However, if the macroexpansion is delayed, this load time is just as much as the compile-time. This decrement of load time was the intention of doing things at macroexpansion time, instead of treating `defpymodule` as if it were a function.

What I'd be willing to do is introduce `defpymodule*` (or `import-module`? but it conflicts with the fact that it was a macro in `py4cl`, not that it matters amidst many other incompatibilities) separately that is essentially functional in nature.

**Comment by death** [comment]
The side effects must happen (and take their time) because they get you into the usable state. The approach of py4cl2 is dynamic in nature.

If you'd like to get a usable state in a short time, you need to use another approach, which may not be so difficult to add to py4cl2. You could generate a stub file that contains the defpackages/defuns/etc. corresponding to the Python modules once. Then you just load that file without introspecting Python each time. The issue here is that when the Python side changes, you need to re-generate the stub.

**Comment by digikar99** [comment]
I'd be willing to keep two versions of the `defpymodule` - one with and one without side-effects.

> but if you load the file in a clean environment

Could you elaborate the use case here? Do you mean deployment?

**Comment by death** [comment]
You know, I actually misinterpreted the issue that caused me to write this patch.

What actually happens is I have two different modules having a form like `(py4cl2:defpymodule "matplotlib.pyplot" nil :lisp-package "PLT" :reload nil)`. So if I compile and load them, one after the other, the second module won't have a good expansion and so cannot be loaded stand-alone.

**Comment by digikar99** [comment]
Okay... I can see where this is coming from.

And yes, the behavior of `:reload` should not be what it is now: one proposition - if `:reload` is `nil`, surround the `(progn (defpackage ...) ...)` form inside a `(unless (find-package ...) ...)` form; any other suggestions?

**Comment by death** [comment]
Right, `(unless (find-package ...) ...)` sounds better than the status quo. Especially because the consequences are not defined by the CL standard if the package already exists and is at variance with the definition implied by the form. For functions, `fboundp` can be used.

As long as the side effects are only there to compute the expansion, this may work in practice, although it doesn't feel very good...

**Comment by digikar99** [comment]
Another thing I agree about side-effects is that compile-file should not result in the creation of new packages or functions, the way it does now.

**Comment by death** [comment]
Well, if it's not the stub approach, you do want to create packages etc. at compile-time, so that the names are available, function calls are checked, etc.

**Comment by death** [comment]
I'll test this change soon... for now I notice it passes `~D` to `format`; likely should be `~A`...

**Comment by digikar99** [comment]
Okay, TIL: compiling a file containing a defpackage form creates that package. So, in that manner, the semantics are good enough.

Re: ~A instead of ~D, right! This code resides from a time I was much less familiar with common lisp conventions.

**Comment by death** [comment]
The latest change doesn't work very well with `:reload nil`. During macroexpansion `make-package` is called, so `find-package`in the expansion will return true (in the same session) and nothing will be done.

**Comment by digikar99** [comment]
Not fixed yet; there are some other errors pertaining to "if find-package returns nil, then one cannot read the form containing symbols in that package".

**Comment by digikar99** [comment]
That should have fixed the `:reload` thing.

**Comment by death** [comment]
It seems to work for the use-case I described, thanks.
Still, I feel strongly about this issue and likely to continue with the approach taken in this PR.

**Comment by digikar99** [comment]
Yup, I will probably build upon this PR post a few days to add a `defpymodule*` and `defpyfun*` that do minimal work at macroex-pansion time.

**Comment by digikar99** [comment]
The way things currently are, even `:reload t` has a correct behavior only in the limited sense. Say if a quicklisp library `py4cl2-user` uses `defpymodule` with `:reload t`, and the library gets updated on the python side. Then, IIUC, the only way to proceed for the user of `py4cl2-user` is to delete the cached/compiled files. And that looks bad.

**Comment by digikar99** [comment]
Hopefully [this](https://github.com/digikar99/py4cl2-tests/commit/4df3ee77495d23f37a16377ebce4f6c34eaf12ec) does it.

Thanks for the PR! I do wish this were simpler, but I am out of ideas at the moment.

**Pull request merged**
